language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO=1.3
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=1.3
    - python: "3.4"
      env: DJANGO=1.4

install:
  - pip install Django==$DJANGO --use-mirrors
  - pip install -e . --use-mirrors

script:
  - pip install 'djangorestframework>=2.3,<2.4' --use-mirrors
  - python setup.py test
  - pip install 'djangorestframework>=2.4,<3.0' --use-mirrors
  - python setup.py test
  - pip install 'djangorestframework>=3.0,<3.1' --use-mirrors
  - python setup.py test
  - pip install 'djangorestframework>=3.1,<3.2' --use-mirrors
  - python setup.py test
  - pip install 'djangorestframework>=3.2,<3.3' --use-mirrors
  - python setup.py test
  - pip install 'djangorestframework>=3.3,<3.4' --use-mirrors
  - python setup.py test
