name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install -U pip
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: python -m tox -e "py${{ matrix.python-version }}"  # Run tox using the version of Python in `PATH`
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:

